### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mchalupa** [staticafi/symbiotic#13]
- [x] add verifier missing types (mainly __VERIFIER_nondet_bool)
- [x] slicer sigsegv removing undef - fix the undef!
- [x] when slicer do not find slicing criterion, say TRUE
- [x] add klee_assume() to all malloc + calloc calls (that the pointer is not null)
- [x] make EGENERAL bound to KLEE: ERROR: not to 'now ignoring error on this loca'
- [x] fix truncateToNBits bug in klee
