### ISSUE TITLE
Add support for LLVM 10 and GCC 10

### ISSUE THREAD

**Issue by lzaoral** [staticafi/symbiotic#147]
Hi,
the upcoming release of Fedora 32 is going to be shipped with GCC 10 and LLVM 10 and it is just a matter of time until they appear in other distributions as well. I have made some changes to the tools used by Symbiotic, so that they stay compatible:

- [x]  `dg` - mchalupa/dg#314
- [x]  `sbt-slicer` - staticafi/sbt-slicer#1
- [x]  `sbt-instrumentation`
    - [x] staticafi/sbt-instrumentation#43
    - [x] staticafi/sbt-instrumentation#45
- [x]  `klee` - Compiles fine.
- [ ]  `llvm2c` - Compiles fine as it already uses c++14. However, some tests fail. See: https://pastebin.com/LUExLBP4
- [x] `sbt-transforms` - #148 

Edit: Add `sbt-instrumentation#43`
Edit2: Add `sbt-instrumentation#45`

**Comment by mchalupa** [comment]
> `sbt-instrumentation` Does not compile for me. It looks like the master branch is not compatible with dg's master.

Well, it must be compatible with the `dg` ref that is in symbiotic (as a submodule).

**Comment by lzaoral** [comment]
Yeah, that makes sense, sorry. The PR for `sb-instrumentation` and LLVM 10 is ready now.

**Comment by lzaoral** [comment]
I have pushed another PR to `sbt-instrumentation` that fixes compilation of `jsoncpp` with clang 10. I've used a system version of `jsoncpp` from Fedora's repositories when porting `sbt-instrumentation` itself so I've missed this.

**Comment by tomsik68** [comment]
As for llvm2c, the resulting programs are correct, so I think you can mark it as ok. The problem I see in the build log is just variable naming.

**Comment by mchalupa** [comment]
Based on the last comment I'm closing this issue. In the case of misunderstanding, feel free to re-open it.
