### ISSUE TITLE
metabug: incorrect answers

### ISSUE THREAD

**Issue by mchalupa** [staticafi/symbiotic#29]
This bug is for gathering information about Symbiotic's incorrect answers
- [ ] heap-manipulation/dll_of_dll_true-unreach-call.i #27
- [ ] loop-invgen/heapsort_true-unreach-call.i #28

---
- [ ] bug in floats #16

**Comment by mchalupa** [comment]
obsolete
