### ISSUE TITLE
TODO in near future

### ISSUE THREAD

**Issue by mchalupa** [staticafi/symbiotic#60]
- [ ] witnesses!
- [x] break infinite loops in llvm, not in C
- [x] make externally initialized globals nondeterministic
- [x] loop-invgen/SpamAssasin...
- [x] finish support for signed overflow
- [ ] get rid of the last leaks in slicer
- [ ] add implementation of round, floor, ceil, trunc (floating)
- [x] malloc-never-fails
- [x] create one instrumentation script for memsafety (it will be more efficient)
- [x] check unsupp after slicing
- [x] instrument valid-deref
- [x] slice with valid-deref
- [x] merge svc15 to symbiotic

Not in rush:
- [ ] Make new README.md
- [x] use cmake when building KLEE

**Comment by mchalupa** [comment]
The near future is over!
